// <auto-generated />
namespace Fundally.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removegrantstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removegrantstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201309042335515_remove grant status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
