// <auto-generated />
namespace Fundally.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FundingCycleAreas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FundingCycleAreas));
        
        string IMigrationMetadata.Id
        {
            get { return "201309042345182_FundingCycleAreas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
