// <auto-generated />
namespace Fundally.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addgrantstatuscorrect : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addgrantstatuscorrect));
        
        string IMigrationMetadata.Id
        {
            get { return "201309042337317_add grant status correct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
